apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-cgw-tokens-encryption: ""
        vault.hashicorp.com/agent-inject-template-cgw-tokens-encryption: |
          {{- with secret "transit/git/decrypt/team12-ycs-tokens" "ciphertext=vault:v1:5fb1OVjXJPYXjxC+B+FsxrZmA764Doln1ZhD5qHTKjTCFRqCHKgm/ZMZGcZKU1VZTkr3Hw8RBKP6I7LinuMOLUui2fETC1Q1g4fyr7a8oMbycfq7zEPzch9QHAc5zzkivEE6FzKNrBYU1X+4U57Nr5lFfOw3" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-tokens-jwk-secret: ""
        vault.hashicorp.com/agent-inject-template-tokens-jwk-secret: |
          {{- with secret "transit/git/decrypt/team12-ycs-tokens" "ciphertext=vault:v1:Cz/OrTSmyF9DQOUWA58ey5fqD2tssuYiCh7ScbbcvGpFJxrYzMwxryuI7M/3u+ifIvzEsH2Wdfnw7bCAVxRujdr3lkqqdh6OItcDzrDJ23aex0sGRuzyq3H/LwtUCLNGl2W8agy8Mw2KoPb2VHKW5gMrZ4HDzW4sSC8KdX21StP+VlZ7WcYmXpSPg0PcbQ9vaIMsmO5/WvcBV0x2YbSGBtT+g6eyIGOKIPuLzNRt/UPh0U/jBABuQALMXwGTuiYBjLf2q4q5Eup+1xZq9MSqMM8+lD6G4Cxc58zbnQKxhPfAnn6z8IE98GAfgbIQ9laRPrHEY/Ltzi1rcO4sxSx7F37J/kFRyrNhXO+0AWhsXlz/JmpwMsP0MYpwmiUW03cxM/p0KXRwDeGHXzavK9RbrPKdgmPYzwLzFf0H0AMJlilUpW5Fhp/uDY53/bGrcB427iG8wJIWSPQxRmIUVJG/Ia82nAzqrg7cIxqB/SmFsabcttFe9o7xqxdLNcfUhavPbe5b2yEviyLqBU7M/52K+IR3vzf3rZAuUFQRqfjG97JKX3zMwzJcBXmHoHX2b4vQ3W+pF4lTFfGzauEVppZUf1XCa4uUwTE1Slz0yyQ1oXRa3hLg0vIxQxC/6WExqJlCR3Hb+XXL/7V3mAv/KkEMC3LIjpQq94QdvdOYE9XzJVdGBROEyvucjIKab3vWi7F2j7Cjx/z22RjZPfsM/N/yKvcvjvkfp2dcTEL1n7kJRcsI14heWOirPi0TnOxqfihjKHa4YNmxRqGkoAZSmP8zgJ4xvx/DrR6BRhX+AM9uuVLVzS9N0DNhlWmwqovbw58+nmL+e2jzCj3V2WSV5P1b6I5yFD+fEDbsqYj1ok1QjYGoY3Wlxa5WgHqedjNNv8Dh7+tQlpRoRWQgYDyz2FicZOkS8LLb3v8iEvN8kkH0Tl4pxKMj66KrzaI06g/P5hiFhSrWs2LwsdGbUd9mz0obqzjc1pQslzonOmIcwkRM2YjH8Dy6WE98NPFqEGTGSvuaGslRtW4xBFHXIfleo8x5tB4PEzrRvQt/bYatUwwwdKZbGSUYK8Trgs0orMKeKyPqxWXlFk4=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: JWKS
          {{ .Data.plaintext }}
          ----------
          eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6IjI4MDhmMDNkLTEwNTAtNDVmMi04YzAxLTljMjQ0MWUwNTBhOCIsImFsZyI6IlJTNTEyIiwibiI6ImxSYUo3MzhiYmlNVXBtVEZMVlhpb1pkN3U5VDlxbTZMU0g1RmRXMUFVckpKRy1FNGZvNm5fMzBfZnRVS2M0Wlpxb3RsSi1TdnVqSHZxZk5UYlZrVnk0bTRqLXlWZ1RRTlAtT0lzZ1RSRVZja2NPazB2OGJUYVFBTEIzdUNMQTd4ZERycjI0SzM1dFM1RTZrRFFROG05UnZIaVFrNG93TkxUODFQZXZIa29IMWxmZ1V3T1pIZlhMekpCcWpfUFhQb1NJVDF5OVNma0NuN00wMGVhMjhuMnhXYkdYVl92ajhiaEpoS1NYQjJqbmxIWE8yUUVYSDZ2OFZvRU5sOUNhV3lqa0owdUpQUEN5alJZTzQtUDJGOTJYdzg4UkMwckdHSC1BQV9zSTlsOHpPSHUyTUtGQUw5dHhpMmlyVUJxOWJJYXlUV3Ywc2pCYnRIbV9ob3B5d1ZhdyJ9
          {{- end -}}
