apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-cgw-tokens-encryption: ""
        vault.hashicorp.com/agent-inject-template-cgw-tokens-encryption: |
          {{- with secret "transit/git/decrypt/team4-ycs-tokens" "ciphertext=vault:v1:lgKlzOimQgjxCOImiCoOIlRX2AeBSyTX9vU6fRfzQihIVHvLp7wmWCOEqiefo6AF6EnfHddHBgy/WVykxOt/GbhZIESoKX1reFHTrBi7eWmvlq+0DW25b36RJExxN1QY72GU5+AxV0cPnHTOfErKee5R8QMt" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-tokens-jwk-secret: ""
        vault.hashicorp.com/agent-inject-template-tokens-jwk-secret: |
          {{- with secret "transit/git/decrypt/team4-ycs-tokens" "ciphertext=vault:v1:MyUheh02bKJhjKWVM0akGuGfeUPV1jxnFJggFIF+Lx2QFSPzqIQ9sN4JkVfBKSolchYjS3ABiBoFbfTqAHOwwIFRFgLQF8Yv3F6sXatsJ9BLl80rN+uXa3nA0tGp/GUBwkNpLKvxKW1C97LYVGh2wpfXMrVQTYlKkKOtBWDjgqIMw7aFKX6v8hTC3L44ujyZ80cgcivNLXUEcXQDVV75BU4ALKvEBjkn4wP+aNsCdileeZWTb/gwra7K1egVGTHod6N5IZKteN/RFb4O69crr25SeyGRugZSP2tQaSIdoc3Xp+5EmfInobpqunOlHW9Y89S+KZenc+7i9Dh6tKmTq+yB3iMwhEwkdXC2wXZgP0H6FtPV7J3skpAxfHAobWxCtnLBUKGYDvSygudbz4Y6HhGWpBO0pD8aZzNpEu7h24v70bOxnnXgId0iRlDRIxKQJn5t7MuzgCxPg/w5sFCHAg6jM0i/qFTe263Wp9GwqHYM/GZpj5Qp6906iY+40IxLgh1BFjjFAxCzlq/LhuU3ULJI3k6wPlosiuwpDwxij2n5MOWXB/TqMOfm4/l0/LsBzjII+uk7TM2ytZHyZg1MOovw9umBD8lZ0Q0YIlDfpPLAMGawuFUe96R4BXp99b9foBERvOHGC7KGvaW3eMY8vLF9VzjjtJQaRgZ7xzC7wOMfmtdqyvM1L0CoyVOlvVYtMF22pUl08koQghC8zNvuGrdICeoe6LumSATgh2y10brcSqRoVMXvAbpqduOL3PmFHsL0wteeYewya29kmzFgzokqVab7nLwbrLjh5r8+h/ZhPZg2k2TVwn8nqgttrnIQgNnWTk2WMbFuzi3fRgozML4MtgQKCfCYWHu0BG5RoMghqoL2tjP1Ncs72M/QmPhQPwtzwY8La0/D5O4lsrhf5/+Mf7/2qavfvJnz+r8b1IRe2xvNt2EgiYyn/ubuTl70H/j4iyBT6YnzKy/sFijUeaD/CW6pd9s4XgEhM+jvUIQZ+Ip1f4Iqrf8565l9JAu5Gqg+l2M22JZIrDuhyl5bCNj5QkN7Lyy5EFcq8BqVS538cTgcCP22dcSCLSVU8g/O/RG2olE=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: JWKS
          {{ .Data.plaintext }}
          ----------
          eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6IjI4MDhmMDNkLTEwNTAtNDVmMi04YzAxLTljMjQ0MWUwNTBhOCIsImFsZyI6IlJTNTEyIiwibiI6ImxSYUo3MzhiYmlNVXBtVEZMVlhpb1pkN3U5VDlxbTZMU0g1RmRXMUFVckpKRy1FNGZvNm5fMzBfZnRVS2M0Wlpxb3RsSi1TdnVqSHZxZk5UYlZrVnk0bTRqLXlWZ1RRTlAtT0lzZ1RSRVZja2NPazB2OGJUYVFBTEIzdUNMQTd4ZERycjI0SzM1dFM1RTZrRFFROG05UnZIaVFrNG93TkxUODFQZXZIa29IMWxmZ1V3T1pIZlhMekpCcWpfUFhQb1NJVDF5OVNma0NuN00wMGVhMjhuMnhXYkdYVl92ajhiaEpoS1NYQjJqbmxIWE8yUUVYSDZ2OFZvRU5sOUNhV3lqa0owdUpQUEN5alJZTzQtUDJGOTJYdzg4UkMwckdHSC1BQV9zSTlsOHpPSHUyTUtGQUw5dHhpMmlyVUJxOWJJYXlUV3Ywc2pCYnRIbV9ob3B5d1ZhdyJ9
          {{- end -}}
