apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-cgw-tokens-encryption: ""
        vault.hashicorp.com/agent-inject-template-cgw-tokens-encryption: |
          {{- with secret "transit/git/decrypt/yfb-acc-ycs-tokens" "ciphertext=vault:v1:bsTHNNCmIW+kfZFsa1Tj8+fqsevUzQ0l2Kndcshgt5T+42QuyEmCShKJDDjCvV89BY3Jnws6hAuYKz/VEV19JLuiFB7kHZPvaj2a4jD0KRM/UZPf3Vhs5roXStlgYtvljD1KWPknEFZQKPmcs+qzkl+E89A=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-tokens-jwk-secret: ""
        vault.hashicorp.com/agent-inject-template-tokens-jwk-secret: |
          {{- with secret "transit/git/decrypt/yfb-acc-ycs-tokens" "ciphertext=vault:v1:5fGLI+lEWEOyIfeXfkkaxXWymNfP/bntvJzUh3/daPgTZxq9gF2vTp9HkKh8qX1rnZa6r2K7s5KWbC6XjOX+1w1Ut07fJfe0rs+y8H6w0v7lBdRzVZxB2hRW4gtdYXW0WxxJFLnVrLWGBHnDgaMA1u/Zou27VxM1USqOS9xSAmdXNWWKON4ABLEqV6ALfQ//79fVq39eiW+JhlhituXL5pvyNjQpqOKWeHDibW+QltwRIA/QpS5jt432ifzcmwWPUqikgKOvDFWbBEgndzVKzRfBPn8mC12tvWuaxJFfJ2LXM9tYnRe66odMPgoJV5/Ac1p8vH0aKW96HTYC2SR1T7Bbj5VTtAz9Bx3vXwdmX0FWe+/s6EEVpUPRmsTUOudGrQpkpfKP0gFjHZ1pXN2nLybMVEjWC1X2sIMjLphPnH2cPShhgCH/9ZYXKXohxsrft0CY7rwntus6ywY0sIAZeHsIAhczA4tbDzr8Mt4D3x4aUBL1gjzsAvikWo7qwyBEofcZ/QlAIqKcS3+tcqkPzm9W2mOs4L6LdO7fBa88tpxrdymdfpk5IAzz2mWDwyqNNOE4rRxURPAFtjKE+lkOfoWNaf11zmJM8dn0g3Fmu/86iVt35DJSdamEiju+BaI7vCzzLbCnoTVKKelp70yG/DOOxTBGWw0uYPVjgBhyZylsJeu6Krt251Kvi6DUaZQ01y6NfDiw7QDNkC6YGuX8tgKZ9KjiPM+f4dgW0fdnwxUcX3++kDMp/UZ/SG18AlsJb/aVK8Ob/GN0qPNMhJJ+/Dl9BA+tYAjuxzCi4MI+Em35e6AO2ZHcd8+dYyPqueHtvsZ5vNwju9oWlb5EixXEWMmeXwGpcC5TvlLts0Wi21ETKHvL8sGEfMPv/UNFfzbKL0hMnP7Ncbf9RpZ5Ox4O4PtMHUhnUuYI5O5AHAm/ct8o/9pvMTAeZG+lO51MbNY8PPhPb8I8qV6XWxUhyZwqPH5nDOHL/tPFPJAAdSQtzPoVroBqRsp+6ZWORDHQJHCA8GUbDJkAIMT9Cu/EKxbt30nqgV1TaTWpPPlZQRVCxH87aODioMPdPzLZI2XZ2odonRqLsIE=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: JWKS
          {{ .Data.plaintext }}
          ----------
          eyJ1c2UiOiJzaWciLCJrdHkiOiJSU0EiLCJraWQiOiI5Yjk2N2RkYS01ZjA4LTRmMDYtOWFjNC1hZjZhODc2NDBlZTUiLCJhbGciOiJSUzUxMiIsIm4iOiIyQVZpaVJYc3FPSTFOamlEeWVmNXpIa3lueXMwSHhzcWFpYUhMcVJKNmVJVmhNakZEVUNFNTJJWFZxSXN0TFgxVDc5WEpFNlVNQTl0d0RQUWhod1A1dG9iS1FWOXVScFlnWGZuZm4wU3ZJRTVZVGlYcFJyVm9ZbEs0ZjVBSjdERzRXRVlNbnJSRzF5U3J1LWxXcWdoYi1iS2VDaTA3cDhYc0ZhaXZFNHVKUG53eXhRMUg2dGRaMTNldElNZG43a3dMcWQwX3NKVFNmVWRqRloxV292ekV0Rm1hSGc1WWxjd2NNbi1ycDh6bmlmOUtRVE5rVEVTbFdQaTV5ZlFqUVcyUlRfMnR6a2dyaEdKZzZkRDNXOFY5ZzF3ZTNaSzIwd3VnWkYweG9ac3dTaEJwVkxPWW42Y0xVNHl1NHl0ZmdDR1A2MnFrWjYxR3V6XzFDNDRjSkhvdXciLCJlIjoiQVFBQiJ9
          {{- end -}}
