server:
  port: 8095
spring:
  data:
    cassandra:
      keyspace-name: ycs_tokens
      contact-points: 10.13.11.4
      username: cassandra
      password: cassandra
      datacenter-name: eu-central-1b
      port: 9142
      ssl: true
service:
  providers:
    url: https://ingress.ycs.team4.yolt.io/providers
  crypto:
    url: https://ingress.ycs.team4.yolt.io/crypto
  yoltbank:
    url: https://ingress.ycs.team4.yolt.io/yoltbank
  tokens:
    encryption-shared-secret: Fdh9u8rINxfivbrianbbVT1u232VQBZYKx1HGAGPt2IFdh9u8rINxfivbrianbbVT1u232VQBZYKx1HGAGPt2I
yolt:
  deployment:
    namespace: ycs
    environment: team4
  vault:
    enabled: true
    auth:
#      service-account-token-file: /path-to-vault-token-file
      service-account-token-file: C:\\workspace\\tokens\\vaultToken
    address: https://vault.vault-dta.yolt.io
    tokens:
      auth:
        path: team4/k8s/cluster%d/pods/%s
      secrets:
        path: team4/k8s/pods/%s/kv/tokens