server:
  port: 8080
  servlet:
    context-path: /tokens
  tomcat:
    threads:
      max: 4
info:
  appName: tokens
  appVersion: 0.1
logging:
  level:
    ROOT: INFO
spring:
  main:
    banner-mode: "off"
  kafka:
    consumer:
      group-id: tokens
yolt:
  commons:
    swagger2:
      enabled: true
      paths:
        or:
          - /tokens.*
    error-handling:
      prefix: T
  vault:
    enabled: true
    authentication:
      role: tokens
      kubernetes-path: "${yolt.deployment.environment}/k8s/eks/pods/${yolt.deployment.namespace}"
      service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
    secret:
      enabled: true
  client-token:
    verification:
      enabled: true
service:
  tokens:
    access-token:
      expiration-time-in-sec: 600
    client-token:
      expiration-time-in-sec: 7200
  providers:
    url: https://providers/providers
  crypto:
    url: https://crypto/crypto
  yoltbank:
    url: http://yoltbank/yoltbank
  clients:
    url: https://clients/clients
  users:
    url: https://users/users
request-token:
  validity-in-sec: 10
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /actuator
  server:
    port: 8444
    ssl:
      enabled: true
      key-store: /vault/secrets/keystore.p12
      key-alias: keystore
      key-store-password: dontchangeit
  endpoint:
    health:
      group:
        readiness:
          include: readinessState, cassandra, kafka
springfox:
  documentation:
    open-api:
      enabled: false
      v3:
        path: /springfox-v3/api-docs
springdoc:
  override-with-generic-response: false
  paths-to-exclude: /springfox-v3/**, /swagger-resources/**, /v2/api-docs/**
