apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-tokens-jwk-secret: ""
        vault.hashicorp.com/agent-inject-template-tokens-jwk-secret: |
          {{- with secret "transit/git/decrypt/team6-ycs-tokens" "ciphertext=vault:v1:B05U6RKsdoOXpM1zSYTpT+oN35qe/7VfEt4tpwfOkuqXJgNkHmr0kGsi9YUwpudTV0PLNn2Ifxt0CqusIc6/lS7DTAFohzzOZic1noO+bZfZ8Tk7NozBC0b/VGzfaN/tAQiHqVW2/VnHMUKkKIq7LmvPwPdenzRK6t0fr9QACNLdgT49nKE67aOkr2fE362KzXhBXNUsH3nH/jXGpfouNMlUm2fwtWkx4dRMJJtebrcCm81ebsnmsXTcAdF4hizvTJVgEZDhsq4pRk6R6cv0bkH/LRJmiStNW5s+K77ddJWW1PRRDBez8tp8kjtmwr9rZnK7Dre8MmceiaTuwQ7YxqFRg5SN2vPYm9XmqhARCCtAsQ9eZgS7F4Idv7l9GNEjWM4FvOzWv514AXI8UsHpubBTyuAoieSMoC+B1n6pfsIbS2yxX6zNW9E/A4wa3R+67b0s0MPOL3wcZ+teLtnBZYsXfjtz3xkEGnXBlZ+xBkcVI0Acs7uhMT7zTf1rGvQyc56DgdBnS8Z34UMXCnDiyBcf1PwalUAJoIS5yfYf1EKNSnCgFY4jvarCoFV5+fpdMJFXtE6zFrGE/rvmuVBpmJ9njFDkR12vZ5rsc+deF9gPzjUl+WoncQSvvXBfYQw5az2SHpT7d5I8XjKnzK5P2Sr7hHNZWJekcCiPgcMs7D/4k6uJPByD6TgNxQrhRNpHhwTlaopIURzcH1t4aO3WbmPaclfpVpleT5P0WIK6aI1R7330AeHRyRlUC3VacI2HPcXVJuCc7BNSGNqXD75vjlbiWvKKAT4sRFWlNHO9djwm3SVF25u6bFiNX/DWZc8ZuG84kVDxhViaBIQMDSKelWrL+ZIy3q/O527bFcge1+VwwLBSY9IgDIvZ4D8dwfcgg9Zmb+iMrfmEXnK3aIuo+fb8QwbLHZd6Ecrr5OJh486LOpOUSjk7cYJH7e5PQ8ILBLvY943zCHiPrQAjQ3wSgaZ5SYq0ADI6rcrq4TYUY/13CA5UrC7O2BAIzw9JgO+eaFREca6Xf9pG5718M4r41KNLg1bAhRNzt9Tzue6kXjWdly3qJyiSLo+up7M2lWCKC0cU2os=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: JWKS
          {{ .Data.plaintext }}
          ----------
          eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6IjI4MDhmMDNkLTEwNTAtNDVmMi04YzAxLTljMjQ0MWUwNTBhOCIsImFsZyI6IlJTNTEyIiwibiI6ImxSYUo3MzhiYmlNVXBtVEZMVlhpb1pkN3U5VDlxbTZMU0g1RmRXMUFVckpKRy1FNGZvNm5fMzBfZnRVS2M0Wlpxb3RsSi1TdnVqSHZxZk5UYlZrVnk0bTRqLXlWZ1RRTlAtT0lzZ1RSRVZja2NPazB2OGJUYVFBTEIzdUNMQTd4ZERycjI0SzM1dFM1RTZrRFFROG05UnZIaVFrNG93TkxUODFQZXZIa29IMWxmZ1V3T1pIZlhMekpCcWpfUFhQb1NJVDF5OVNma0NuN00wMGVhMjhuMnhXYkdYVl92ajhiaEpoS1NYQjJqbmxIWE8yUUVYSDZ2OFZvRU5sOUNhV3lqa0owdUpQUEN5alJZTzQtUDJGOTJYdzg4UkMwckdHSC1BQV9zSTlsOHpPSHUyTUtGQUw5dHhpMmlyVUJxOWJJYXlUV3Ywc2pCYnRIbV9ob3B5d1ZhdyJ9
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-cgw-tokens-encryption: ""
        vault.hashicorp.com/agent-inject-template-cgw-tokens-encryption: |
          {{- with secret "transit/git/decrypt/team6-ycs-tokens" "ciphertext=vault:v1:sYpCt99dgdoe3J/iTY4e8/txkDSBu9C/Lr4CzTIaSgVFF8UxWCAC+WJGhFy5bjnosHmu3KmVJXZuF21LOi4xP5Ae45EICffDAAfwa2BePpuMFx7Ohg+AfLkyRCms+ZGKOi8RZUJJbMEwILsNKvLJitb3C52y" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
