INSERT INTO clients (id, name) VALUES (297ecda4-fd60-4999-8575-b25ad23b249c, 'Yolt');
INSERT INTO clients (id, name) VALUES (a2034b12-7dcc-11e8-adc0-fa7ae01bbebc, 'Test Client');
INSERT INTO clients (id, name) VALUES (5aeafb70-6e5e-4cf5-a13e-3023846fc928, 'Yolt test');
INSERT INTO clients (id, name) VALUES (43d71a36-cf05-47c6-a2ca-c426eb5537e3, 'Performance Test');
INSERT INTO clients (id, name) VALUES (a5154eb9-9f47-43b4-81b1-fce67813c002, 'ING France');
INSERT INTO clients (id, name) VALUES (9fd1c25c-3bc9-4af7-8d51-424440bcdfb4, 'ING Belgium');
INSERT INTO clients (id, name) VALUES (44b561bf-bf83-4ddb-ac54-59e52b75081f, 'ING Netherlands');
INSERT INTO clients (id, name) VALUES (c18df055-d2ea-460c-9252-f6bc0eddca15, 'ING Poland');
INSERT INTO clients (id, name) VALUES (91a91388-d505-46bf-bf6c-c0ffa920c2d0, 'CASY main client');
