apiVersion: batch/v1
kind: Job
metadata:
  name: tokens-cassa
  labels:
    team: yts-clients
    git.yolt.io/group: backend
    git.yolt.io/project: tokens
    git.yolt.io/tag: $(TAG)
    yolt.io/config-server-tag: $(CONFIG_SERVER_TAG)
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-cassandra: $(ENVIRONMENT)/database/cassa/creds/$(CASSANDRA_NAMESPACE_PREFIX)tokens
        vault.hashicorp.com/auth-path: "auth/$(ENVIRONMENT)/k8s/eks/pods/$(NAMESPACE)"
        vault.hashicorp.com/role: tokens
        ca-certificates.yolt.io/inject: "true"
      labels:
        team: yts-clients
    spec:
      containers:
        - env:
            - name: keyspace
              value: $(CASSANDRA_NAMESPACE_PREFIX)tokens
            - name: cassandraNode
              valueFrom:
                configMapKeyRef:
                  key: spring_data_cassandra_contact_points
                  name: cassandra
            - name: cqlDir
              value: /cassandraUpdates
            - name: namespace
              value: $(NAMESPACE)
          image: $(DOCKER_REGISTRY)/tokens-cassa:$(DOCKER_TAG)
          name: tokens-cassa
      restartPolicy: OnFailure
      serviceAccountName: tokens
  backoffLimit: 3
  ttlSecondsAfterFinished: 0
