apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokens
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-tokens-jwk-secret: ""
        vault.hashicorp.com/agent-inject-template-tokens-jwk-secret: |
          {{- with secret "transit/git/decrypt/team9-ycs-tokens" "ciphertext=vault:v1:CKjUKLtGvx0ditI1xJHQgt1AczxmnBrG3FJ7mbEk5sTwmk/XpXWwi1RU3p6YQ3ykhbnmrKQP9gsZPCHxdGFshVvnjn1gqg1od8o6y7fU22dbShADH1MtMTgPACNKezM2MUTmHXPHrqkFe+xZIj05EqleHL2SGdRSrHmt8we+Pc5/vg44TxY2532/tHmgoG3ZuSxUVOgTGLi9DX+K12byKv8rYRNd4ywe8aLc/78O9jUbfGOvCEomVhIo5KnwmYPZv07SQCbFELXi3MbF0sH9nBqcY1cj33et8AOFh0YTNFdpYfHxKyO6BHE45D9fyF2dvN4HevoTmDrfIAGTBmaD1hvKaofV8/SjUMyC2jU0Vat+eIqXPbtA5twiF1cmunnIjsWn/14bRmHhO2Q1ZN8T26/b6FnBqK+y9rEhfSk5clYILMFH4+JQj/wHdIC56EVyq+N8E8y7/2pTa+BKCI5FzxAIyMFcm0AE3rzLmyYn/xg/FPH6rrbsvyh10hixVotOGStpxl2Ku5NtjyyOdjrDUxKnGFSswbLaOwiuCSA01PNNebntxQ9OZqcG/KUxB4ol35y9xSC7ePmcTFVctFIbyhaixNmM7KDI6zG4c27O5IfVBJtoAhTkMR2VaHkzfQyIwMvCpwx3Ib4AiyHkYi03tNmhQOlVpjd20NbgnW/9twhFiQKv8tdnuyEAVX8G3AcogoABiadrwCAkltSFIB/ZjB87zSdTM+NUmNduAGMK5LdGNeFVM1a9XV5Po0+UQyNO+jbnJCik/QHhrUSUXgArldu9KNzzAFuqhvN3gxOsWY5ICUYMEYezxu+U3KcnN4CP8PONI4C7lZ9yyJoROyuKVTjRGLCPF36gr7hKhkUjmqcV7E69aeJfLtqP10yhvK2AzoCsiigywU9naplqyMVOFkBzSs3i8i+MQ44SR4uT6SR4QU78X+XmGPnGOJqNtmF+D1LUWeciufYsjGDPH4cAv5+cc+ivbjr+JAYrhspWKxJ2/zS/JmmDqss0BRIz+7+6D0OB5m5ItRlWdSE3RdC62m2vVw6tcooyGxzL/gZ8TuWYaqjkZr4WN5j7Tf+aP83HluU2rdY=" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: JWKS
          {{ .Data.plaintext }}
          ----------
          eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6IjI4MDhmMDNkLTEwNTAtNDVmMi04YzAxLTljMjQ0MWUwNTBhOCIsImFsZyI6IlJTNTEyIiwibiI6ImxSYUo3MzhiYmlNVXBtVEZMVlhpb1pkN3U5VDlxbTZMU0g1RmRXMUFVckpKRy1FNGZvNm5fMzBfZnRVS2M0Wlpxb3RsSi1TdnVqSHZxZk5UYlZrVnk0bTRqLXlWZ1RRTlAtT0lzZ1RSRVZja2NPazB2OGJUYVFBTEIzdUNMQTd4ZERycjI0SzM1dFM1RTZrRFFROG05UnZIaVFrNG93TkxUODFQZXZIa29IMWxmZ1V3T1pIZlhMekpCcWpfUFhQb1NJVDF5OVNma0NuN00wMGVhMjhuMnhXYkdYVl92ajhiaEpoS1NYQjJqbmxIWE8yUUVYSDZ2OFZvRU5sOUNhV3lqa0owdUpQUEN5alJZTzQtUDJGOTJYdzg4UkMwckdHSC1BQV9zSTlsOHpPSHUyTUtGQUw5dHhpMmlyVUJxOWJJYXlUV3Ywc2pCYnRIbV9ob3B5d1ZhdyJ9
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-cgw-tokens-encryption: ""
        vault.hashicorp.com/agent-inject-template-cgw-tokens-encryption: |
          {{- with secret "transit/git/decrypt/team9-ycs-tokens" "ciphertext=vault:v1:oJ3YRSMpapbdZnHkkCyltuaEpyeRMNpRyi7iITFEW7iIgZWsMaXX4JZLYh+ZDjwyFe6N48gzSf9AeosDKpUo0nfFMBjnddl4xTuAIRgm9SnB+v7mMlJWuZ5mllfKNUoWpzxpylIh3V0o+dfDgk/TVjrKXqUa" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
